# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build app

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - "*.json"
      - .editorconfig
      - ".github/**"
      - .gitignore
      - LICENSE
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - "*.json"
      - .editorconfig
      - ".github/**"
      - .gitignore
      - LICENSE

jobs:
  build:
    name: Build application
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.1
        with:
          dotnet-version: "6.0.x"
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: "6.x"
      - name: Restore NuGet packages
        run: |
          dotnet restore --locked-mode
          nuget restore .\sampleapp\SampleApp.sln
      - name: Add msbuild
        uses: microsoft/setup-msbuild@v1.1
      - run: dotnet build
        name: Build
      - run: |
          msbuild .\sampleapp\SampleApp.sln
          dotnet test --no-build -c Debug ./test/IISExpressBootstrapper.AcceptanceTests/IISExpressBootstrapper.AcceptanceTests.csproj
        name: Test

  deploy:
    name: Publish application
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/') && success()
    defaults:
      run:
        working-directory: src/IISExpressBootstrapper
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.1
        with:
          dotnet-version: "6.0.x"
      - run: |
          echo "Github ref is: $GITHUB_REF"
          if [[ "$GITHUB_REF" =~ ^refs\/tags\/([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(\-[[:alnum:]]+)?)$ ]]; then
            echo "Version is: ${BASH_REMATCH[1]}"
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            >&2 echo "Not running for a tag. Is this a problem with Github Actions?"
            exit 1
          fi
        name: Prepare version number
      - run: dotnet restore --locked-mode
        name: dotnet restore
      - run: dotnet pack -p:Version=$VERSION
        name: dotnet pack
      - name: Publish package to nuget.org
        run: dotnet nuget push bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
